apiVersion: v1
kind: Service
metadata:
  name: {{ include "fta-profile.fullname" . }}
  labels:
    {{- include "fta-profile.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fta-profile.selectorLabels" . | nindent 4 }}
