mode: deployment

image:
  repository: otelcontribcol-dev
  tag: "0.0.1"
  pullPolicy: IfNotPresent

command:
  name: otelcontribcol

extraEnvs:
  - name: K8S_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName

clusterRole:
  create: true
  rules:
    - apiGroups:
        - ""
      resources:
        - events
        - namespaces
        - namespaces/status
        - nodes
        - nodes/spec
        - pods
        - pods/status
        - replicationcontrollers
        - replicationcontrollers/status
        - resourcequotas
        - services
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - apps
      resources:
        - daemonsets
        - deployments
        - replicasets
        - statefulsets
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - extensions
      resources:
        - daemonsets
        - deployments
        - replicasets
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - batch
      resources:
        - jobs
        - cronjobs
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - autoscaling
      resources:
        - horizontalpodautoscalers
      verbs:
        - get
        - list
        - watch

serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: fta-mstr-addon-open-telemetry@fta-platform.iam.gserviceaccount.com
  name: fta-mstr-addon-open-telemetry

config:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

  exporters:
    googlecloud:
      project: fta-platform  # Replace with your GCP project ID
      traces:
        endpoint: "cloudtrace.googleapis.com"
        use_insecure: false


  processors:
    batch: {}

  extensions:
    health_check: {}

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [googlecloud]

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    protocol: TCP

service:
  type: ClusterIP

podLabels:
  app: otel-collector