mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib
  tag: "0.51.0"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: fta-mstr-addon-open-telemetry@fta-platform.iam.gserviceaccount.com
  name: fta-mstr-addon-open-telemetry

Config:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

  exporters:
    googlecloud:
      project: fta-platform
      trace:
        endpoint: "cloudtrace.googleapis.com"
        use_insecure: false


  processors:
    batch: {}

  extensions:
    health_check: {}

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [googlecloud]

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    protocol: TCP

service:
  type: ClusterIP

podLabels:
  app: otel-collector