apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-${unit}
spec:
  acme:
    email: imamariefrahmann@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-${unit}
    solvers:
    - http01:
        ingress:
          class: nginx