nodeSelector:
  iam.gke.io/gke-metadata-server-enabled: "true"

serviceAccount:
  name: "fta-mstr-addon-external-dns"
  annotations:
    iam.gke.io/gcp-service-account: "fta-mstr-addon-external-dns@fta-platform.iam.gserviceaccount.com"
provider: google
policy: sync
google:
  project: "fta-platform"
  zoneVisibility: "public"