{{- if and .Values.ingress.enabled (eq .Values.ingress.controller "gke") .Values.ingress.gke.frontendConfig }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ include "fta-dev-gce-app.fullname" . }}-frontendconfig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fta-dev-gce-app.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.ingress.gke.frontendConfig | nindent 2 }}
{{- end }}