{{- if and .Values.ingress.enabled (eq .Values.ingress.controller "gke") .Values.ingress.gke.managedCertificate.create }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "fta-dev-gce-app.fullname" . }}-managed-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fta-dev-gce-app.labels" . | nindent 4 }}
spec:
  domains:
    - {{ .Values.ingress.hostname | default .Values.global.domain }}
    {{- with .Values.ingress.gke.managedCertificate.extraDomains }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}