apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.appSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
stringData:
  .env: |-
    {{- range $key, $value := .Values.appSecret.secrets }}
    {{ $key }}='{{ $value }}'
    {{- end }}
type: Opaque